name       = "photo-bucket"
main       = "worker.js"
compatibility_date = "2024-01-01"

[[r2_buckets]]
binding    = "BUCKET"
bucket_name = "photo-bucket"

[triggers]
# crons = ["0 * * * *"]  # Run every hour
crons = ["*/5 * * * *"]  # Run every 5 minutes


[observability]
enabled = false
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[observability.traces]
enabled = false
persist = true
head_sampling_rate = 1
